 Node.js CI


  
    
      - main
  
    
      - main
  
    -  '0 */4 * * *'


  

    ubuntu-latest

    
         [20.x]

    
    - Checkout repository
      actions/checkout@v3

    - Set up Node.js
       actions/setup-node@v3
      
         ${{ matrix.node-version }}

    - Install ffmpeg
      |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - Install dependencies
      |
        npm install -g pm2
        npm install

    - Start application with timeout
      |
        timeout 14520s npm run zokou
